# Deliberate faults for tools/mutate.py: (name, exact snippet in the contract, replacement).
# Each must be caught by at least one test.
MUTATIONS = [
    ("AGGREGATE does not become POOL",
     "scope = SCOPE_POOL if outcome == AGGREGATE else SCOPE_FRESH", "scope = SCOPE_FRESH"),
    ("POOL does not draw down",
     "        if record.scope == SCOPE_POOL:\n            return int(record.cap_amount) - int(record.used)",
     "        if record.scope == SCOPE_POOL:\n            return int(record.cap_amount)"),
    ("FRESH is not capped per claim",
     "    def _payable(self, record: CapRecord, amount: int) -> int:\n        return min(amount, self._remaining(record))",
     "    def _payable(self, record: CapRecord, amount: int) -> int:\n        return amount"),
    ("a cap is active at once (no acceptance)",
     "            state=CAP_PROPOSED,", "            state=CAP_ACTIVE,"),
    ("acceptance ignores the text hash",
     "        if given != record.text_hash:", "        if False:"),
    ("text hash not normalized",
     "            text_hash=self._hash_text(normalized_text),", "            text_hash=self._hash_text(clean_text),"),
    ("anyone may accept",
     "        if caller != record.claimant_wallet:\n            raise gl.vm.UserError(\"Only the named claimant may accept or decline\")\n\n        if record.state != CAP_PROPOSED:\n            raise gl.vm.UserError(\"This cap is not awaiting acceptance\")\n\n        given",
     "        if record.state != CAP_PROPOSED:\n            raise gl.vm.UserError(\"This cap is not awaiting acceptance\")\n\n        given"),
    ("a declined cap may still be accepted",
     "        record.state = CAP_DECLINED", "        record.state = CAP_PROPOSED"),
    ("claims allowed before acceptance",
     "        if record.state != CAP_ACTIVE:\n", "        if record.state == CAP_DECLINED:\n"),
    ("a recorded claim draws down at once",
     "        self.claim_payable[key] = u256(0)\n", "        self.claim_payable[key] = u256(0)\n        record.used = u256(int(record.used) + self._payable(record, amount))\n"),
    ("anyone may confirm",
     "        if caller != record.author:\n            raise gl.vm.UserError(\"Only the author may confirm or reject a claim\")\n\n        key = self._require_claim(cap_id, record, index)\n        payable",
     "        key = self._require_claim(cap_id, record, index)\n        payable"),
    ("anyone may reject",
     "        if caller != record.author:\n            raise gl.vm.UserError(\"Only the author may confirm or reject a claim\")\n\n        key = self._require_claim(cap_id, record, index)\n        self.claim_state[key] = CLAIM_REJECTED",
     "        key = self._require_claim(cap_id, record, index)\n        self.claim_state[key] = CLAIM_REJECTED"),
    ("a claim may be decided twice",
     "        if self.claim_state[key] != CLAIM_PENDING:", "        if False:"),
    ("confirm does not draw down",
     "        record.used = u256(int(record.used) + payable)\n", "        record.used = u256(int(record.used))\n"),
    ("reject draws down",
     "        self.reject_note[key] = clean_note\n", "        self.reject_note[key] = clean_note\n        record.used = u256(int(record.used) + int(self.claim_amount[key]))\n"),
    ("confirm records the asked amount",
     "        self.claim_payable[key] = u256(payable)", "        self.claim_payable[key] = self.claim_amount[key]"),
    ("pending count not decreased on confirm",
     "        record.used = u256(int(record.used) + payable)\n        record.pending_count = u256(int(record.pending_count) - 1)",
     "        record.used = u256(int(record.used) + payable)"),
    ("used-up pool still takes claims",
     "        if self._remaining(record) <= 0:\n", "        if self._remaining(record) < 0:\n"),
    ("claim cap off by one (21 claims)",
     "        if int(record.claim_count) >= MAX_CLAIMS:", "        if int(record.claim_count) > MAX_CLAIMS:"),
    ("claimant may be the author",
     "        if clean_wallet == author:", "        if False:"),
    ("fail-safe flipped on unparseable output",
     "            if not isinstance(data, dict):\n                return {\"outcome\": PER_EVENT}",
     "            if not isinstance(data, dict):\n                return {\"outcome\": AGGREGATE}"),
    ("validator accepts any valid label",
     "                return validator_outcome == leader_outcome", "                return True"),
    ("reserved token not checked",
     "        if (\n            self._contains_reserved_token(clean_label)\n            or self._contains_reserved_token(clean_text)\n        ):",
     "        if False:"),
    ("same cap may be opened twice",
     "        if cap_id in self.caps:\n            raise gl.vm.UserError(\"This cap already exists\")",
     "        if False:\n            raise gl.vm.UserError(\"This cap already exists\")"),
    ("note length cap off by one",
     "        if len(cleaned) > MAX_NOTE_LENGTH:", "        if len(cleaned) > MAX_NOTE_LENGTH + 1:"),
]
